-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price text,
  image_url text not null,
  product_url text not null,
  source text
);

-- Enable Row Level Security (RLS)
alter table products enable row level security;

-- Create policy to allow public read access
create policy "Public products are viewable by everyone"
  on products for select
  using ( true );

-- Create policy to allow authenticated users (or service role) to insert/update/delete
-- For simplicity in this demo, we'll allow public insert/delete if you want to test easily without auth,
-- BUT for production, you should restrict this.
-- For now, let's allow all operations for anon key to make the Admin page work without login implementation.
create policy "Enable all access for all users"
  on products for all
  using ( true )
  with check ( true );
